version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: askracha-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Override or set additional environment variables here if needed
      - PYTHONUNBUFFERED=1
    # Uncomment if you need to connect to other services on the host
    # network_mode: host
    # Or use a custom network
    networks:
      - bot-network
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot-network:
    driver: bridge
